name: Automated Geopolitical Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
      
      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Python dependencies
        run: pip install requests google-genai PyGithub jsonschema
        
      - name: 4. Debug Secrets Availability
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "Error: The GH_TOKEN secret is not available or is empty."
            exit 1
          else
            echo "Success: The GH_TOKEN secret was found."
          fi
          
      - name: 5. Execute Automated Update Script
        run: python seed_database.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
