name: Automated Geopolitical Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run_analysis:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
      
      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Python dependencies
        run: pip install -r requirements.txt # Assuming you create a requirements.txt file
        
      - name: 4. Run the Seeding Script
        # This step still runs your temporary script to create the archive.db file
        run: python seed_database.py
        
      - name: 5. Commit the new database file
        # This new step checks for any new or changed files and commits them
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data: Seed historical article database"
          file_pattern: "*.db" # Only commit the database file
