name: Automated Geopolitical Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
      
      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Python dependencies
        run: |
          pip uninstall -y google google-api-python-client
          pip install -r requirements.txt
        
      # ⬇️ ADD THESE NEW DEBUGGING STEPS ⬇️
      - name: 4. DEBUG - Show requirements.txt content
        run: cat requirements.txt
        
      - name: 5. DEBUG - List installed packages
        run: pip list
      # ⬆️                                     ⬆️
        
      - name: 6. Execute Automated Update Script # <-- Renumbered
        run: python automated_update.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
