name: Automated Geopolitical Dashboard Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
      
      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Python dependencies
        run: pip install -r requirements.txt
        
      - name: 4. Execute Automated Update Script
        run: python automated_update.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
