name: Automated Geopolitical Dashboard Update

# Define the schedule and manual trigger
on:
  # Cron Schedule for every 30 minutes (0 and 30 minutes past the hour): 
  schedule:
    - cron: '*/30 * * * *' 
  # Allows manual triggering from the Actions tab for testing
  workflow_dispatch: 

jobs:
  run_analysis:
    # Run the job on a free, standard Ubuntu virtual machine
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        # This step pulls your code (scripts and schema) onto the runner machine
        uses: actions/checkout@v4
      
      - name: 2. Set up Python environment
        # Installs the correct Python version (3.11 is modern and stable)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Python dependencies
        # Installs the necessary libraries: requests, google-genai, PyGithub, jsonschema
        run: pip install requests google-genai PyGithub jsonschema
        
      # IMPORTANT: Note that the Python script will automatically create the 
      # DashData/data.json file if it doesn't exist yet, so we don't need a manual step here.
        
      - name: 4. Execute Automated Update Script
        # Runs your core logic script, passing the encrypted secrets as environment variables
        run: python automated_update.py
        env:
          # Injecting Secrets (MUST match the names you used in GitHub Settings)
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # <-- Use the new, non-conflicting name
